version: '3.8'

services:
  ping-producer:
    image: ping-producer
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - rabbitmq
      - postgresql

  ping-consumer:
    image: ping-consumer
    ports:
      - "6000:6000"
      - "6001:6001"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:management

  postgresql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
