version: '3.8'

services:
  ping-producer:
    build: 
      context: .
      dockerfile: ./dockerfile-producer
    environment:
      RMQ_HOST: "rabbit"
      RMQ_VHOST: "/"
      RMQ_USR: "guest"
      RMQ_PWD: "guest"
      AUTH_CONNSTRING: "Server=postgresql;Port=5432;Database=Auth;User Id=postgres;Password=postgres;"
    ports:
      - "5000:8080"

  ping-consumer:
    build: 
      context: .
      dockerfile: ./dockerfile-consumer
    environment:
      RMQ_HOST: "rabbit"
      RMQ_VHOST: "/"
      RMQ_USR: "guest"
      RMQ_PWD: "guest"
    ports:
      - "6000:8080"

  rabbitmq:
    image: rabbitmq:management
    hostname: rabbit

  postgresql:
    image: postgres
    hostname: postgresql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "15432:5432"
